local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK(data) m=string.sub(data, 0, 500) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end
local folder = game:GetService(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('wVdYEwEbwUPATMuTloMxgaLjDtgNavtDbnXdMgrdNtnTlnFEEljBAcFpZxHhLiYdjrFnWKThublQQgjlIJwVxAIcwBfxtTPhXOYyEdVgfbECjYusrvLoNPoAiEnGsWbhVKAzVsvpfSRRxLFhexyGkZcdhmWutqepVFoAutSnQxkdVmjJLJkihHZCsciKQneKoKksRUyKsomJZGdgWcPkFExtQzZUyGtjXIqYIiTNljNqlpDNHtsxujUaoCBCWUmyaqWZkeWiFNVokWxHiJQfRLKjkDQXwlBnJvdhuQKzzXJTsDyqHVLYXcKhNeWzzxaPugDFwGAdSccGrotAjamriONFDITfXMSrAOpLndhejFRUHFoJdHuaQhmzBSZcDtzruDUmXXrArVHEXsRbyjBAdpzRiYPwfGBSeoVUYLkERPeSTHijKXMouUFpLjAxBRnrkNKvfqwgEJEGMmQxSeMjZVZqDBjQwpigXezvmfTEjceSBTtlRIWhUmVwbGljYXRlZFN0b3JhZ2U=')):WaitForChild(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('faCAndNShxJEIVhznjWrNzlEmdJDIoILqdkcSFIGnilGBkOiEPVdWuYUCMZadqgvvdOJXZjvYCqKIznAwxFViTdFRYoMWBkPrzrOOgnZDDipmXEDevpwcHHrRiKxtVGMtEJSRmOUOrgcwxKASavnPrTnypEwfgqGGULhSfXebGNYcYypLBpzuXODjGDisjrOPNKjlEkfPEcFOVPcrsrVwSyPLOCrydNNWqWwNEnxFLzKLUYsVAMMuhMyEJvLWrBqeUBfApBvTCtQvhMHXHtQQnwoQcQIYyFGIdoCtDgxmTiRhFogNMWAlbansipSmnMWuZddRSZduVjqiKQCDIWscReKvBbUEKEcXJQobYQLRQmoGkWdvfsdUlSJQvtHMkMlcDBNDXZPDOwUCXQCgfYHbKRlFVugkeORvXiWdRPesSZjSLIGFpOnLhsUJHqMuuTnMJjXTEMGUmMzpjMYWutrBEfLegZVGcoyALUfgwcwRqENVTdEVoVlY2xpZW50YWRh'))
local setdata = folder:WaitForChild(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('itcvCeAhsWpEiCNHYKAYLYWCMxinvEqLwaBpnsmSWUeqayoWUrGjFEKnKZltZBPLjNuRroMiGYLArDWyuKBFiyobSOhLbdskDgHLttKtlhxySFBUQYLXDhjNWlxjjAPvcPhbCajrBFchlcngalGaaIEHnRxToJgIsujQSmrJaBtozScYSRIZMRLDATszbxFPVkVmGAiDsdjBrYpBwZCNoLOtuNWdyekINUnTpmBgRBMPdTcRoPTIcjJeIrZLucoMjjjgfHcumeAplJYgcfadLTyOnQRPKymDiXCatTVNJZIUGyWwPmvSisvoIDoBThyqFmGLlvGNTvINCDUNTKfScVlvOKvZafXioTcregNWYbXaHRDDdrALDDUKwEwGgKashaCFAxaBgaHXatyvmhMywHCqwKcGmzqLukEYbXcxRGbBSXplYCYgKPkdDFbkduQoJaNXywQKAdahyjubpVEvPVuaXgnRJqbBsluGUCMEmorJopijkptUU2V0RGF0YQ=='))
local getdata = folder:WaitForChild(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('qkfJQxjnYCuCLdQHAFIfChZQgUJmAceudCgOlsinTtHZjZuEAUzKwkeBErvNdvJkpmzBJHcuinNxbFdHQnUAemuTcetRDmRzCzpkCuOAXEYyTCLKdMKbBVYtPLlxAHOvrlAIZNhhdjwrJElSMLZZbANcSMLMfkqjTQhVRIjzRsXwjxuwuoKnoVZhJhTXhLyLazugHLtsiECUCgYKJaqyhFrQHawjusLSPxZqBsXOmJmAmxhJWBSVzvPdzDpkpsbFeWHmqbjhZKBBjkXvYcszWpMALXvELorAYalKXdvCQdhiPguouhGJReSoGhEmbbNiUqIuGqWojQPRhfSsBPBChBbSrTRQXKzTvPtlcmsdjaCAwAagWEFfDpPEJkiCPyldsJLkJnVHXjvyqwljQXDnLzVUulBUromMQdsHeaFTxXmRmvVeEThiSjAVtuRcFGzCIyuyOLonXfflRmeKWmfhmOqjVjnqZrGLqnuNAqYPbZsTplsMfWDbR2V0RGF0YQ=='))
local incrememntdata = folder:WaitForChild(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('OqlXiAFAfSnxNhmgRDOvWyVBDZqDWmEEuWNaQRroaSXbgDrUftwnnavfcqwRHYPkXanQjcMxaDoaJLyVPlQFlQSgIkfaSZuVAkqGUBoCJlNSuiVsRBIfuWVwWgmlXYBJKZFENZaFPYhLQeueSCuxgvpVMbhTLioLzYvEZsesAfnzFXEYMEDmtRDmfyKHhsOisVdfZCzwTIDqqpwdCOBKcDEvOFtysgGtELCinKXKDseJZhjyhBwuZyWtqszojTuWMFDajbcygzaSiCLIsBUUuEzOaJXxbGfiFqdFoesaCZzsYDDigIKdLPEgYScLEsACYeQTqJHIzaNOTUlVBMFNNAgiIlsAznUnSAMMWdFsKzOOoinFQhKHbCkqHNtFlSFovtvtWbUCGcboHTJNTcGISNUIvTGMjwlZnAmAUpciOSjWbuyyQMsTNAcBBeUWrrketGNgaWsmrSUjjyBWEvJlHjSJWPooBSVqNHBjyOANUAoTLxJxcTbLSW5jcmVtZW50RGF0YQ=='))
local updatedata = folder:WaitForChild(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('xCpWuQoyEahDKuwDIpKIaYaomJeXsavAIpBECnxhhNitPuCuQBeIiZnWABYUYBZpgdxVzfbZMjkkcagIAkxyZNwRtuZgjaHYyVGFkqEVJKWzMQnAyWJvRlyKjLwIZWbabOMEdpwdeNCkECGJgxESwvpLugrLGXVVaPqUNINRjApdhnShXdHaLMRjeyFdxkZOIExcsrBUOFWYWVDFYDNrxxkQRbKrFSGPQOBVbMzIZidRElgjRlkmGNOUEAnwGJVKZklYOgqzmvfVDsccldaLQuuvtvvjmwyWRwyUrKYCPKlEqKETudHWLJGFXPatGTgDzUTmTvABjVMrYjVTygnLlYTrtzKMuHXXcLnfWlwbQauAamCawLkLyfCPpuRnjrZbNHMJxxJIMLHzhOkzEVmlXKnjuDrkNGppzwRVLFObdpopVzVgondVYKVlRgsDtPTXNuvckYrSRmvZYCThGXQEsynPWOAwttLOumRADTKkNBNigYCRrQIBVXBkYXRlRGF0YQ=='))
local removedata = folder:WaitForChild(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('MpWuDmazZriJDCLIfbippNKzXxaDWrmIDhjDvFpwejkKwkWlEIeSsiJONALucYoDkNrOhydLePGvkmooEBGmoPffhxHgJkaNEQpLvYjLjcaVvegKeDzrbicugmRTsmdQeFKnjNXouxiZcJbbOHeZLIEANnlViayauXnfFnvDKUikpCJcsaPhBybocwZyHBEugdbPmXkJbvdYFqKClAjygqvrJmYCCGwIlSwbtncpbfMnoCmsqDYoagzgtGDHtVGrfTUUzqPWmMVhDbGpCyFZNZlKJXQvTGoOtfurpwVfQuoNTOgWLyaxCMKcghjuqEazkZOlyqjAZShqnieGSGUXfSIFeYMPxqfnAQYdZGBvFfaAdLUOanhESNQVjAcgICRZjHwAuhOZGkzbtoJWylaFCTMsfAGMMrvCEURpGebIQsRQKazsoxsyFiRwzxoghfRQuVZaqYrtJkOozIMWgBWIIupTNnrjvpFFYfUABliKxANwGUgPnGePUmVtb3ZlRGF0YQ=='))
local dsv = game:GetService(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('gAJxqDpYWLKjDnmAJttvOnwSJAnDtyNVwBHHNRIaNOfYXiDFsLDpjUFvcDDqSNnzgauDDijijUBKdTKvVpbpffHIKGsZTwfReOoJzubkcJFqpeJkFtMRLXkcQZVkWUYhAuBDnICXxlctiaFXvLXlyrZjGFSchfYKxeFhvzeWfXyAcOufyXGTjCXqqKwkuJBzkGLMIWXeGVKdzIaqZFEMRyocVswfEOjnpzTVjPWrqNAkHYzGzYzrFwvmimlmBXjySCPyokByGszPLPtjgoPVgBFGYRjIsaPaVEaqochbKdfppnwaLKAcBEzteoHgYdtBedZuwNRYHmfojrlGTSozdRNqFioTRNJEFLbxLuXeHrGREKqjDzFmsABIOlApPYMvTVzdQathWjNEraxeuqerZpGWbFXGKZrdpYUwCRbbAFzWYVNWAPkbWueFuUvAmQNtjPkHfEoETGZmxwEusIKgpOFQYfffKdFhtnTxbBYayFukaaxWoqhnRGF0YVN0b3JlU2VydmljZQ=='))
local config = require(script:WaitForChild(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('xXKQACfBSlzvVTlRMqlLnMOsZMLhzpMqxYkJIxnXxbisHHdfpTpSdkOBFNVqXNSrkfOWnQTOUkzyRQqXLAUouCDyFplesHpXeXuKgvnUmfEzMYipLJntkBNyNqrzPzrYdGkAkvQbwOVEnTqWlwmJrNYQpWOUciSBQmLLEDpdLeNdEhRuxjjpUdlvOGhdREQImZpEVvrqdGnZvYihpHUWAkxiSeSmIcQsghFBLDQlyWuVgkerzCiECqjCrPcBHmoFubWKaWmDavBuCcphesiDnBlUozqkfctmyFTpepGwmRNEGehPXpkPVOYRDaYPzNFivGtzqLlprxbWizkZxJmpwwJSAyETRPSWJDbNnHcHFpAVAZYnHValtjhAEwObrpmxcoKqNeTUAOGvMwEVXvuOysMwUJJZbdbGQdEsiZkhfLqoAvIYbliyAxbWFTpECCzOsaBptNksWDPdADOpQZhDwgZRYZAqRgfjDIIeJbhZaeVplPlZqzvUY29uZmln')))
local key = config.Key
local kickoninckey = config.kickOnIncorrectKey

if typeof(key) == eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('eSszGxphYbqZJbNIWGoCXkQSilepnusBLZehTmjQAkJiaxAvXcPyxpvtenvOcuLQercXLJrZLSJFWKdkxvLmboYPFWsRhmKklpvcGAtCaGpDlRpRTKlgTYmYYDzcpvAzidNtEchCWapKntuniVSBBGsgtmnDZTleFaSQMUiStLEIsiKFQHtIwKEgZNQurMrxprhwqDUjhBvPwfarQgjHmhUImnlAYLycveKPMRKgBXyzOSgIrgaOuuYMpcWXFJbOvcfPRWXExDyouDTbgrMzopTkHHnxWxJZuEcIuiqcjTUeNJdoXzQHZDeYZjiZwJdKxvgbuQibeJxldzzLECfsSmKtfOoVIpmcioBugkQnFCobdhifylgiZIDvGEGRggBLaBcIQxaIyRizMpPoyGJWLkFWuPYGErBEpBwXzdCePXTEjKazrqdHPBuZOcrQnaKlMsbSOiVrnvjqyBAFgiEIWlWHsPktqGJbBmjZkyyQNfXihrTgOfBgYm9vbGVhbg==') then
	error(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('NjHSiRNIWsDBiiCKskBBhfQRlwWaSPcHTMUatUagRhNDSCwtVzcYtAEBzlQtIUZyWHMtsXpoVMGYRRFqWZajOWlQcFTfWhWsWqKdLoPXgJCCvQgGAcLeWWPweGfGpWSKUNuRnKdhIAuIXDIVMPbbUtypFfNClqukJDGHBmEmegeuPzOvGQXVEcCcHArWVJoDcMwNxYFaXawVPKyMADKxmkdqnPCVlBHkStLNLhUOdTHqsFfvXhYaQmFwHKGoZtnZntVjIdYhEKRClyeNUmPAOnkRNYzeBGUzCiCIIjeVLxUhEsfMwTALYWhAzBUNqKfBjCsmPQymqqDmtPYwXZhHzPGxaEVlyQcFcfdpIDKwqTfhmTwCDGhmsJAxqIQFsbeQvGMKdjxyvmvzCDpGVVfzZMLvimlqYRvlpbATEnLQboubJMHEQmTaSbhRwBTrtUJwxsAzZSvuEIwROpWdGSKARoshsUTqBvvZoSQEYWKmAMdnnmsukirQSW5jb3JyZWN0IGtleSBjb25maWcu'))
end

if typeof(kickoninckey) ~= eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('QUCvTFGAGKBCQwLqacoeNzCRWHdGoEVusQMeVkHWjIRClNURqDnrgqzjEbVcvqtTVLPiAfxVAuPrDDcCPHalIiAFBlooRHSBXkhHHkVmGxzuwbTSBKidaGPypFFHAKYaizdKehJBpHsurOSQaKISsnCwyYTwdwDlruvZzXjqAuSEZTrUAWZATXRflFPGXwNSFxBjxlmsSPviQtmWDZxYnciNQOTNdTtuUzutAaNRXGTHEqjkVaAydvxBzgaKslpSOPvKxkAVeDpgIacRRVCtGgcMDNZDlbZNcSJdGDfzEDPAXqCteoWpTJgoyaIUQIvYmmmFuvGIGjjdlPYNckvolpgXUuCdyYnrNJQwzMlRCQyOKzfujKQbAhElKbgRusIrKnbHxsRKkjHOQvpAayPWllTyhqaIbfPCEEVOYEelykpWZYKRRBqADsUUyWUlrqOeXhqEjtHQYYrDkrTiXRvjOZagzCsjsGkRfNsLRxaVVsfftiLYArsCYm9vbGVhbg==') then
	error(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('xLuMSQEsfsokXxsCWYAxVmTqfDqQbkCvilTbFkXiGgXSXAlciaoUSepizTBHGNNXyepjffEHvyClXnGVdctKQlcRIypQoxAgOWiyZNdMzDdqjEuySESUsqRJvDSuppNpuaVMKyyNyElTKyCCzAAeuYGefHUYmTQlKwbkzoCAIrNMqgcvEtdcWWePLPzQyQlPvSCvFnYjndXMrpHGMxmZFGcLFpKYxLWfbJaenaOdRQMitmvsGUXpzUqnqiqLCLxAYXTRTjIKUpHZoPpJVlZlDvaDJqidbBejYtEfGTkAkWJfbzvktpRVuYRImpqDUYBAJVHQZdwVJuqunuPhboSabKuXpUKxRksSYWRHWJfseGqSLsoOrWuEQXbklZUlHiOiZBDXCbDjRPJwaCPMRqcLInkrlYnmVUndPYciIIuOSlMJAlZlcuiSZtwvYYWJGKnKwwkROjlxhOYPDrkEvQqDoxXLYKgkUvhHhehaGdlnZRELnuxAxHSySW5jb3JyZWN0IGtpY2sgb24ga2V5IGNvbmZpZy4='))
end


setdata.OnServerInvoke = function(plr, userkey, ds, dkey, data)
	if not userkey or userkey ~= key then
		if kickoninckey == true then
			plr:Kick(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('IuOrKrOEbrvTSlVlTyOJNebSnZMMMKtmxWVTGWkSbiNFYIotEiryEwNVdggDMohBcHlXlLazXrYxGaHtkYwmquMzgnnIsLMreTxAweZEQCJYZGXfuuulTTksOOpzbXbwNXyqvulgokOqNFIdOIcWngSPFAeNqlrudZcJulBzJiMZXoulfbduEDRRXKNJnWQDSAXthjtjOKnGWAvGpxkHklGZEdhkOjQMLWynWvOyHnOUdaQJspyLVoIjClpftjZSGAeegHXwRyMvOPzTkkgMwjOqMBnMYhWaBGkalQmmvrfalZNludvuXHznPkIMDAYlygTkOMmZSYTuRzLWAPVJEHsRgzdObNzXiRdbPWnFPZTEiCZFshjHGxbsTcvNtNZgpLVomIzkwVNKieeJzdvRQgAWAneHLcQrwuPphiTezYInBFdDEvZGFuSQJefrpRUddrxsmkMlNsqUAeaxJFFtMeUNikwtckxFRpmdpfFemYMqPeHmAQaiQXR0ZW1wdGVkIHRvIGFjY2VzcyBDbGllbnRhZGEgd2l0aCBhbiBpbmNvcnJlY3Qga2V5LiBQb3NzaWJsZSBleHBsb2l0IGRldGVjdGVkLiBLZXkgcHJvdmlkZWQ6IA==').. userkey)
			return end
		if kickoninckey == false then  
			warn(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('PLxWdbxkPMIbsmGBuWsMDVXBoMqYmDGyvCteBuobOKBKAsmfoVJJQjKAmPWeuAjHVHzOUQCAMhAHNabWDnEbCkNHXDkHNDeSyfAMlhQQNfQLcvFyDYTwHJoUNDnkalIftAAmBPQhxmuuuolKkSxpWYVemzKEveILDHrxDGFHXSeXJwGhIiFiAlYZpEkcrMnjVnfZMvvtlEngfePvVpCfmogeOEuGdnqKgluSsySTjWgdmYAtDgsTyXqaVTDWqRibLtkbJJtmMAqlHwjehClcfLwvLoPLEixNDsontOopgtLUrASmKMRzLTCoBkslyrbKuQkqZkmoMNACzdAbdWVTNkfMqcHfrFwpyiVFFzxXpGoRleqZmPzntugKiqvOqUukpIaPJkbdzqIFdTZwETuiLrlDOhpasBgvGmuhZrqZHvAvxAwWzXYCYQfwNcLOppJJpsHiQzSCERPMjCJnLEGRcPrxbxyWMRFTtbUkNUdGqhrxwuaIbMDJQXR0ZW1wdGVkIHRvIGFjY2VzcyBDbGllbnRhZGEgd2l0aCBpbmNvcnJlY3Qga2V5'))
			return end
	end
	local success, errorm = pcall(function()
		ds = dsv:GetDataStore(ds)
		ds:SetAsync(dkey, data)
	end)
	if errorm then
		return errorm
	else
		return 0
	end
end

getdata.OnServerInvoke = function(plr, userkey, ds, dkey)
	if not userkey or userkey ~= key then
		if kickoninckey == true then
			plr:Kick(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('gZiGdYWiMUXoJfqVXFUTdkDADxFApaEbYFkWGcTRJAVWyNIlLPsjZRUHgbvirgeNKdhpsfvlybQrnaKsHJHlIXNhwkYwvfqFQFNOpYvjByJjmGonzaAbgFuroNdXlmYKmRFDSCcGSAHeKCBZQjpClJYehcEgntrcPrnjIzqsTXWJBzspEyFTCnjSxJtXSbKPFZTrrWDYkYObzEceDetlqzWOBchbfVXiePMZTFfTagwOGqriFzbbEouPRWRQqCieACmVmZHKqqOzZHpoQeWkOfzRFbcLWXkqKgHQUALodjyLTqwxvrfnSsPAHgvQokVJuhuFetWGJmOMwCDYRksJxEzhUpzFSYqcXkdvceFDoEBGqnBjMuhMSPsGEIYkwyOghEWXDdsLFkZsppUqhmSWMfgEIBeTwfTsWMbbVvVgiocZtIUHoLdpIXyxnJhOsdDDRsTaQdNnONsuJanSdgLywaZlcZyZHWfyOgdlcbIDbCZwPZtDvdCzQXR0ZW1wdGVkIHRvIGFjY2VzcyBDbGllbnRhZGEgd2l0aCBhbiBpbmNvcnJlY3Qga2V5LiBQb3NzaWJsZSBleHBsb2l0IGRldGVjdGVkLiBLZXkgcHJvdmlkZWQ6IA==').. userkey)
			return end
		if kickoninckey == false then  
			warn(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('kHrwlJwQzXFYaTMqFbvLhkGDnfrjBLkNwAbgwFEOUEohzRNwelSQhxBZmqNvKMIjYIVkkUaTLDnMeHwletNHUqmFexaARyoNvEgRchuCavwEKjaNPHPGZSWrOOqlACzvizdEqHMyhsHBAiharcbrNmLwkRVIvQIiXwzXQaFshUGpewFXIZkSxsJOtJglwGAgpOMluvdKOvEXVKgfssxTPDXGLnnerexWeeUfPufViQxaSshcvOeOMVixdTEbWkiBpRCXpiIsZZPjkbGseEMOqPHuNWCTEbhlKORzuFgTDXlbeMvkgjBKUlKUsigiEnJgbAwehxJDbUmjcPBWroKUgPUSauqAwAaiOLmyTAziDWgfKAxfnmkYtUcfmiTPMNoBUhhcQQBHGDDrfaBaoeQqsjYEUimWccMFXWfskSIPHxhPGXQlFZYlVMicVcfDfHQJitkeqKaNhtJWMssXPoJkIXTldGuwcVvdnItalpfectjTvlevpSaiQXR0ZW1wdGVkIHRvIGFjY2VzcyBDbGllbnRhZGEgd2l0aCBpbmNvcnJlY3Qga2V5'))
			return end
	end
	local rdata
	local success, errorm = pcall(function()
		ds = dsv:GetDataStore(ds)
		rdata = ds:GetAsync(dkey)
	end)
	if errorm then
		return errorm
	else
		return rdata
	end
end

incrememntdata.OnServerInvoke = function(plr, userkey, ds, dkey, increment, incrementoptions)
	if not userkey or userkey ~= key then
		if kickoninckey == true then
			plr:Kick(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('COEqerEQJdubuFSatkSbiFOmEinPDqvsURPQBGPPyLccFkTyvijNXNRmevBkUXjPzRruhTVcwIiMcpEwbNHDcgzdgLCiBfMpxwBXFrqCSFcnrHFSfcSeCDxbIEwIVqfvfRTSccToqkfxKMIFnDjpOPsZHjuPfIxNOjoOdsfjqfdvQjgSEpYkLzlhjrrcKUEbTVHcaMjIkLHYJLEVGCOtNcpiReRzDaoCcpNczuDTcLpxYAwLMqzooUYpCCmSUxXdSklmINIvtXnjeDyykqHwijOeWjpRQeyYaupgIKdEEYdODNcvnviajJnCXyafCHlgSImMJvLOpiBZUfhdSzBWEiGIhLgARsEVUYXbhHGTxwCOVvkVTszdBbTtOazgMJFFsNTWkBXTdbEuoYxGLdkIdMaUvqQKtPkijfhegahQMquYrRqdKnFgrGfrtgKimTnUSSJObylYCMerXRetLWaOEBytxpXTfhSaKXqyZmNDFHDdteWaSzxpQXR0ZW1wdGVkIHRvIGFjY2VzcyBDbGllbnRhZGEgd2l0aCBhbiBpbmNvcnJlY3Qga2V5LiBQb3NzaWJsZSBleHBsb2l0IGRldGVjdGVkLiBLZXkgcHJvdmlkZWQ6IA==').. userkey)
			return end
		if kickoninckey == false then  
			warn(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('ybfKpIXwQEwcxmBFeAtosFIpjbaWvWyDxJtrYGikBunKhhDJickOJlojQiIViHKsQHbggPAlZLlIIZizYehdDiRBcpDQsgmAqYWsCWbGYNTiTuGVBzqihzpMtDdjfkJEfLJEPWYAehYShjEnSzqhZNcebhbKrnWZwFpeZYEcGkJmAvUMCPEBvxFrWVtNmPaEOJDQWOTsrAuqKVaRNhJKZiVaQlfczBFaVXWNCsVRZdaqiTVkLXVWZTBYbjocXLmqjbrkrmHwcOyYdkBSDRAmzHnNnGnkcoCrxfiHdhDPzQImTprnnvYUTMNhmBNtfOJbbWRBSlPsTDMZrxwcDVGRTHEKsIFzkIRbvvhiJayVBpQESFaOxHguAYNpiLQOjKRobWBZIyuzmtOnAkAEeqazzSrVYikdCBlTUDHpHCpfVmMMfBlJNrzmZqdZpZahzFajMUeUUYlyVdkvCOOXMiFsMepCqfDrBHxzuSjMwqVVROQWTSCPkubHQXR0ZW1wdGVkIHRvIGFjY2VzcyBDbGllbnRhZGEgd2l0aCBpbmNvcnJlY3Qga2V5'))
			return end
	end
	if typeof(increment) ~= eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('QJrYeUkzPWmBRoQrNuEZYJykkHnHqkpxeYTlRudYzANhlDfEeQBqnjqGPxCACzFAqtdMFiJTSbWHsJEBvWckUTCNtYdRgnLxLefmWmuYMpNWrYlhozJvfHJDulPlrofbnWvhxFkLhIYAcCintHTHicQhaNrdcETkMGlvOJnCTmsPMjwulwBzJClijMhSKXZyDyxZLfhcFGwLQHRCYsMNdaGlHANYHzYFYZDBdgDsiCwLLAOULzduOtxqXbBvGDbegwRmaJtslUKpByzhSlmqlkxAhPmGOjNNBjwiOAzZJCBHYlhCMYTVDnOUnEuGZTSySNhXaQDqsxfnVoacscXhoBwxphYNHPKDGyRIUZUSGBpIuHRElHWXoZSvuKcJDUPnArCqodkyDOXDwbpSnZBLicvZRAZAhqNxvbjbGhSAqzDOXDChApgzhHRHVifqITpixHcQxGLlQwhWachySawTFFZGuhqJkpwwJkDjVVzZpQvWxfUqBmLUbnVtYmVy') then
		return eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('zQDgqAMoiLaryLwurrajvIxvJNOoeNNWnMGEZHefCQqiLMWmsgNmgpiIXPXdECKUEHbbuuZWdTbPUKYlaJVoHvjpJfGesnPwfgcrNherefJBAzIrYvzeskktaiCWrNrFVXLmVYJHcuZQSPtmsVpkLYcfnCLhDvZZOJBGgQdgvRlCgqTFUcyHwWXUOrSfuUVcDxnEkQdpFHsaKWLwsaNxbpwvnYOIVXjnAYaXuUipNYbYwDTCTMicvjXJXsuKUmcDvLzJjpkTSsfPINIwqBKwzCLTZJqRMRNodwLgBHKeBKDxIuTQVafHDGGKzfEmrWEwdwqiUZRooiDSnnHnxjRnHjAStvjWwwloeKNfUePdllwFtsLFPKVVhbqCewJRooZxHumBoJBUltgsJqiDsBaIKlNwhzLBkkvecJrXscnkGoreXLfltTQIVpSbumcPUjFhokNEiNMVKaLPiHjjIbacOyWfdjfGbNCNXKVDafpSlpeGcesurEIgSW5jcmVtZW50IHZhbHVlIG11c3QgYmUgYSBudW1iZXI=') end
	local success, errorm = pcall(function()
		ds = dsv:GetDataStore(ds)
		ds:IncrementAsync(dkey, increment, incrementoptions)
	end)
	if errorm then
		return errorm
	else
		return 0
	end
end
removedata.OnServerInvoke = function(plr, userkey, ds, dkey)
	if not userkey or userkey ~= key then
		if kickoninckey == true then
			plr:Kick(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('GHxoLJfEOYzeaigxzGSpZVjbczkMUkMDajqdOAWOROhWKVMNvqkCMbosXFksUoUxEGJVaDnnOKshzJLAYPCOQoLVYsgtmvozLCZKuyKAqzkPXkXUYkTXyLwdKvuzMVcLwdmWJGgScqMiCqYYGNusIRsBogVGGkDGpvDJieLHjYERWuCPHLPZdKpYqssLeavysCzJnXgcUzhsFwAIKcHRybVmqFJEUdIIfHQUbXvoQzJZWYexFseICCJhIcVxDHMaYpOUBaVyEkFEpdyqJypceVTTbIoittDKYzleoXTndkUuTZVWWWxEdEHrHlukdOOJXaYlhZKZBZhNgVWQfHBpRmzQsEiJsmFPVwCLIKLBoAjbtXkzmOFTGtSFMztgsgYkItCSVqlBXTkGpJxgZNgejRUlqonsWFyqoYtuoTSMrjbPvNUgTzIhLOeoTzPxCkjtHcvyAietZjFdGbSbLnpSZGOzEoBFFqkQlfPYOuZNfinGbyLHFHmfQXR0ZW1wdGVkIHRvIGFjY2VzcyBDbGllbnRhZGEgd2l0aCBhbiBpbmNvcnJlY3Qga2V5LiBQb3NzaWJsZSBleHBsb2l0IGRldGVjdGVkLiBLZXkgcHJvdmlkZWQ6IA==').. userkey)
			return end
		if kickoninckey == false then  
			warn(eITNCUQxeMfTpWzZOtsMcqqzmtOmEoPHfQbQtCOcBEdBhgDlczwaRXzZeIUBxMrTjeSFyOHHcTERJCndK('asupirbiqVwEKRMrAORPQdAkIkHOsNaXjtMEUJIJIRKWRsEPCnYUVJbAKVyeBAoaHTgrAVPzQMEJafCVQvqmyjwdNxNuiXqZvBghjuJbwLdcAwghGFwUfjBoyoIytsacCPeyaDxSfrisecPUrLzOUNHogarXXCqlEuLEDlCiSTmtUrKimaQewLpXKSLQwwQfyqafzLdFuEyeKZqugxJsaUTNfseWYXxsSzDocBSSIrVvbhPNJsmtEUSNUCCtNjUJLloDebXOLkPRKffDsbZqbkLzeXbJERtDuKrYozHSdWHCJzuyvhliGVmFEAjyXTAOqHDTiheHfgLHpeesTwgFrDfwancFkFnqbpeXIJQmLbhgJXVLLGsJhbyNhnSkECZDCtbImsxsjQtyYExNskmzifqIEIMQEpJaPsrzBHRZWjpwHMrBNAkOsRdIAlCWEptlPFVhHFrZOoPoyVBTUiDlWDHfuPftVfhnerYGUQTEXjpqEUHEzeknQXR0ZW1wdGVkIHRvIGFjY2VzcyBDbGllbnRhZGEgd2l0aCBpbmNvcnJlY3Qga2V5'))
			return end
	end
	local success, errorm = pcall(function()
		ds = dsv:GetDataStore(ds)
		ds:RemoveAsync(dkey)
	end)
	if errorm then
		return errorm
	else
		return 0
	end
end    
